### PR TITLE
Remove usage of Java 8 features so that this plugin can be run on Java 7.

### PR DESCRIPTION
**Pull request by smccauliff**

### CODE REVIEW

**Comment by vivin** [comment]
@smccauliff How comfortable are you with groovy? I was thinking of changing that whole class to a groovy version. That will also remove the dependency on Java 8.

**Comment by smccauliff** [comment]
I know enough groovy to get by with gradle files.  I am not comfortable enough to rewrite all of VersionUtils.java into groovy and possibly the files it depends on.  For code that is going to be reused many times I prefer using Java rather than groovy anyway.

**Comment by vivin** [comment]
@smccauliff Same here, which is why I wrote it in Java 8 first :) No worries though, I was planning on switching it to groovy anyway to deal with this issue so I can go ahead and still do that - I just prefer idiomatic code (easier to understand at a glance). But I really appreciate you helping out!

**Comment by vivin** [comment]
@smccauliff merged in the change so closing this one. Thanks again!

**Pull request closed without merging**
