### PR TITLE
Spock changes and shield style for CircleCI badge

### PR DESCRIPTION
**Pull request by Vampire**
- Update spock to 1.1
- Fix some small errors in the parameter injection
- Use shield style for CircleCI to better fit with the other shields

### CODE REVIEW

**Comment by vivin** [comment]
@Vampire hey! Sorry; just seeing this now. I was pretty much on vacation from middle of May until around July 2nd after which I started a new job, so I wasn't looking at this stuff.

**Comment by Vampire** [comment]
Don't worry.
1. it is just a fix for the tests that does not fail in this case, but I reworked it a bit when contributing this methodology to Gradle itself and thereby found some minor issues I thought I PR here too.
2. Long ago I remembered why I don't like the approach you take with this plugin and don't use it anyway. :-)

**Comment by vivin** [comment]
Ok -- I will be making some changes soon to deal with a new version of JGit and maybe include some small enhancements to deal with submodules. So I will merge this stuff in before that.

BTW, what is it that you didn't like with the approach? I will try to improve it if I can. :)

**Comment by Vampire** [comment]
Unlikely, it is the whole concept.
I don't like having access to the VCS being necessary to build the software.
It is ok to query some information from the VCS, storing it in some file e. g., but it shouldn't fail if VCS is not available.
If you e. g. export the sources, you suddenly cannot build it anymore.
Or if you use e. g. HanDouts and its server-side checkout feature, the build agent also has no access to the VCS.

**Comment by vivin** [comment]
Well, I built this largely to work with versioning _with_ VCS, so that was a core assumption. So yes; it's unlikely that I will change this.

**Comment by Vampire** [comment]
I know, that's why I didn't ask for it. :smile:

**Pull request merged**
